
export const RECEIVE_TRAIN = 'RECEIVE_TRAIN'
export const REQUEST_TRAIN = 'REQUEST_TRAIN'
export const REQUEST_TRAIN_FAILED = 'REQUEST_TRAIN_FAILED'

export const RECEIVE_ENTITIES = 'RECEIVE_ENTITIES'
export const REQUEST_ENTITIES = 'REQUEST_ENTITIES'
export const REQUEST_ENTITIES_FAILED = 'REQUEST_ENTITIES_FAILED'
